/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 drone.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/drone.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh028.geometry} material={materials['Sel_Red.001']} />
      <mesh geometry={nodes.Mesh028_1.geometry} material={materials['Sel_Yellow.001']} />
      <mesh geometry={nodes.Mesh028_2.geometry} material={materials['Sel_ORange.001']} />
      <mesh geometry={nodes.Mesh028_3.geometry} material={materials['Sel_Green.001']} />
      <mesh geometry={nodes.Mesh028_4.geometry} material={materials['Sel_Cyan.001']} />
    </group>
  )
}

useGLTF.preload('/drone.gltf')
